// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const LOCAL_DEV_EMAIL = 'local@123sports.dev';
export const LOCAL_DEV_PASSWORD = 'local123';

const localSupabaseError = {
  message: 'Supabase is not configured in this local environment.',
  name: 'LocalSupabaseUnavailable',
};

const localUser = {
  id: '00000000-0000-4000-8000-000000000001',
  email: LOCAL_DEV_EMAIL,
  user_metadata: { full_name: 'Pedro Local' },
};

const localSession = {
  access_token: 'local-dev-token',
  refresh_token: 'local-dev-refresh-token',
  token_type: 'bearer',
  expires_in: 60 * 60 * 24 * 365,
  expires_at: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365,
  user: localUser,
};

const LOCAL_SESSION_KEY = 'on_tennis_local_supabase_session';
const LOCAL_SIGNUP_STUDENT_KEY = 'on_tennis_local_signup_student';
const LOCAL_PROFILE_KEY = 'on_tennis_local_profile';
const LOCAL_BOOKINGS_KEY = 'on_tennis_local_bookings';
const LOCAL_RESERVATION_SESSIONS_KEY = 'on_tennis_local_reservation_sessions';
const LOCAL_PRICING_KEY = 'on_tennis_local_pricing';
const LOCAL_CHECKOUT_ORDERS_KEY = 'on_tennis_local_checkout_orders';
const LOCAL_CHECKOUT_ITEMS_KEY = 'on_tennis_local_checkout_items';
const LOCAL_PAYMENT_ATTEMPTS_KEY = 'on_tennis_local_payment_attempts';
const LOCAL_BOOKING_RESCHEDULES_KEY = 'on_tennis_local_booking_reschedules';
const LOCAL_NOTIFICATIONS_KEY = 'on_tennis_local_notifications';
const LOCAL_STAFF_INVITES_KEY = 'on_tennis_local_staff_invites';
const LOCAL_CLASS_PLANS_KEY = 'on_tennis_local_class_plans';
const LOCAL_CREDIT_GRANTS_KEY = 'on_tennis_local_credit_grants';
const LOCAL_CREDIT_ALLOCATIONS_KEY = 'on_tennis_local_credit_allocations';
const LOCAL_CREDIT_LEDGER_KEY = 'on_tennis_local_credit_ledger';
const LOCAL_SITE_SETTINGS_KEY = 'on_tennis_local_site_settings';

const defaultLocalProfile = {
  id: localUser.id,
  full_name: 'Pedro Local',
  avatar_url: null,
  phone: '(51) 99999-0000',
  birth_date: '1992-05-14',
  blood_type: 'O+',
  years_playing: 4,
  skill_level: 'Iniciante',
  emergency_contact_name: 'Contato de Emergencia',
  emergency_contact_phone: '(51) 98888-0000',
  medical_notes: 'Sem restricoes medicas informadas.',
  bio: 'Aluno local para testes de agenda, aulas, perfil e fluxo administrativo.',
  dominant_hand: 'Destro',
  games_won: 12,
  aces: 34,
  cpf: '123.456.789-09',
  address: 'Rua das Quadras, 123 - Porto Alegre/RS',
  guardian_name: '',
  guardian_cpf: '',
  guardian_email: '',
  guardian_phone: '',
  referral_code: 'LOCAL',
  referred_by: null,
  created_at: new Date().toISOString(),
};

const localBookings = [
  {
    id: 'local-booking-1',
    session_id: 'local-session-1',
    user_id: localUser.id,
    professor_id: localUser.id,
    booking_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    start_hour: 9,
    type: 'aula_individual',
    status: 'confirmada',
    payment_status: 'pago',
    payment_method: 'pix',
    amount_cents: 12000,
    confirmed_at: null,
    attended: null,
    hold_expires_at: null,
    checkout_order_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'local-booking-2',
    session_id: 'local-session-2',
    user_id: localUser.id,
    professor_id: null,
    booking_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    start_hour: 18,
    type: 'quadra_livre',
    status: 'confirmada',
    payment_status: 'pago',
    payment_method: 'pix',
    amount_cents: 8000,
    confirmed_at: new Date().toISOString(),
    attended: true,
    hold_expires_at: null,
    checkout_order_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

const localReservationSessions = [
  {
    id: 'local-session-1',
    booking_date: localBookings[0].booking_date,
    start_hour: 9,
    professor_id: localUser.id,
    product_type: 'aula_individual',
    capacity: 1,
    unit_price_cents: 12000,
    status: 'open',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'local-session-2',
    booking_date: localBookings[1].booking_date,
    start_hour: 18,
    professor_id: null,
    product_type: 'quadra_livre',
    capacity: 1,
    unit_price_cents: 8000,
    status: 'open',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

const localPricing = [
  {
    id: 'local-price-court',
    booking_type: 'quadra_livre',
    display_name: 'Quadra livre',
    price_cents: 6000,
    student_capacity: 1,
    requires_professor: false,
    sort_order: 10,
    active: true,
  },
  {
    id: 'local-price-individual',
    booking_type: 'aula_individual',
    display_name: 'Aula individual',
    price_cents: 12000,
    student_capacity: 1,
    requires_professor: true,
    sort_order: 20,
    active: true,
  },
  {
    id: 'local-price-double',
    booking_type: 'aula_dupla',
    display_name: 'Aula em dupla',
    price_cents: 8000,
    student_capacity: 2,
    requires_professor: true,
    sort_order: 30,
    active: true,
  },
  {
    id: 'local-price-trio',
    booking_type: 'aula_trio',
    display_name: 'Aula em trio',
    price_cents: 6500,
    student_capacity: 3,
    requires_professor: true,
    sort_order: 40,
    active: true,
  },
  {
    id: 'local-price-quartet',
    booking_type: 'aula_quarteto',
    display_name: 'Aula em quarteto',
    price_cents: 5500,
    student_capacity: 4,
    requires_professor: true,
    sort_order: 50,
    active: true,
  },
  {
    id: 'local-price-test',
    booking_type: 'teste',
    display_name: 'Teste',
    price_cents: 100,
    student_capacity: 1,
    requires_professor: false,
    sort_order: 90,
    active: true,
  },
];

const localClassPlans = [
  {
    id: '20000000-0000-4000-8000-000000000001',
    frequency_per_week: 1,
    duration_months: 1,
    price_cents: 25000,
    title: 'Individual avulsa',
    description: 'Uma aula individual com o professor.',
    active: true,
    modality: 'Individual',
    class_duration_min: 60,
    credit_modality: 'individual',
    credit_quantity: 1,
  },
  {
    id: '10000000-0000-4000-8000-000000000001',
    frequency_per_week: 1,
    duration_months: 1,
    price_cents: 29000,
    title: 'Grupo mensal',
    description: 'Quatro créditos para aulas em grupo.',
    active: true,
    modality: 'Grupo',
    class_duration_min: 60,
    credit_modality: 'grupo',
    credit_quantity: 4,
  },
  {
    id: '30000000-0000-4000-8000-000000000001',
    frequency_per_week: 1,
    duration_months: 1,
    price_cents: 50000,
    title: 'Dupla mensal',
    description: 'Quatro créditos por aluno para aulas em dupla.',
    active: true,
    modality: 'Dupla',
    class_duration_min: 60,
    credit_modality: 'dupla',
    credit_quantity: 4,
  },
];

const localSiteSettings = [{ key: 'cancellation_notice_hours', value: '24' }];

function hasSupabaseConfig() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
  return Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}

function canUseLocalSupabaseMode() {
  return import.meta.env.DEV || import.meta.env.VITE_ENABLE_LOCAL_MODE === 'true';
}

export function isLocalSupabaseMode() {
  if (import.meta.env.VITE_ENABLE_LOCAL_MODE === 'true') return true;
  return !hasSupabaseConfig() && canUseLocalSupabaseMode();
}

function readLocalSession() {
  if (typeof window === 'undefined') return null;
  try {
    return localStorage.getItem(LOCAL_SESSION_KEY) === '1' ? localSession : null;
  } catch {
    return null;
  }
}

function writeLocalSession(enabled: boolean) {
  if (typeof window === 'undefined') return;
  try {
    if (enabled) localStorage.setItem(LOCAL_SESSION_KEY, '1');
    else {
      localStorage.removeItem(LOCAL_SESSION_KEY);
      localStorage.removeItem(LOCAL_SIGNUP_STUDENT_KEY);
    }
  } catch {
    // Ignore storage failures in private or restricted browser contexts.
  }
}

function isLocalSignupStudent() {
  if (typeof window === 'undefined') return false;
  try {
    return localStorage.getItem(LOCAL_SIGNUP_STUDENT_KEY) === '1';
  } catch {
    return false;
  }
}

function writeLocalSignupStudent(enabled: boolean) {
  if (typeof window === 'undefined') return;
  try {
    if (enabled) localStorage.setItem(LOCAL_SIGNUP_STUDENT_KEY, '1');
    else localStorage.removeItem(LOCAL_SIGNUP_STUDENT_KEY);
  } catch {
    // Ignore storage failures in private or restricted browser contexts.
  }
}

function readLocalProfile() {
  if (typeof window === 'undefined') return defaultLocalProfile;
  try {
    const stored = localStorage.getItem(LOCAL_PROFILE_KEY);
    return stored ? { ...defaultLocalProfile, ...JSON.parse(stored) } : defaultLocalProfile;
  } catch {
    return defaultLocalProfile;
  }
}

function writeLocalProfile(profile: Record<string, unknown>) {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(LOCAL_PROFILE_KEY, JSON.stringify({ ...readLocalProfile(), ...profile }));
  } catch {
    // Ignore storage failures in private or restricted browser contexts.
  }
}

function readLocalCollection(key: string, fallback: any[] = []) {
  if (typeof window === 'undefined') return fallback;
  try {
    const stored = localStorage.getItem(key);
    return stored ? JSON.parse(stored) : fallback;
  } catch {
    return fallback;
  }
}

function writeLocalCollection(key: string, rows: any[]) {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(key, JSON.stringify(rows));
    window.dispatchEvent(new CustomEvent('on-tennis-local-data-change', { detail: { key } }));
  } catch {
    // Ignore storage failures in private or restricted browser contexts.
  }
}

function localStorageKeyForTable(table: string) {
  switch (table) {
    case 'bookings':
      return LOCAL_BOOKINGS_KEY;
    case 'reservation_sessions':
      return LOCAL_RESERVATION_SESSIONS_KEY;
    case 'pricing':
      return LOCAL_PRICING_KEY;
    case 'checkout_orders':
      return LOCAL_CHECKOUT_ORDERS_KEY;
    case 'checkout_items':
      return LOCAL_CHECKOUT_ITEMS_KEY;
    case 'payment_attempts':
      return LOCAL_PAYMENT_ATTEMPTS_KEY;
    case 'booking_reschedules':
      return LOCAL_BOOKING_RESCHEDULES_KEY;
    case 'notifications':
      return LOCAL_NOTIFICATIONS_KEY;
    case 'staff_invites':
      return LOCAL_STAFF_INVITES_KEY;
    case 'class_plans':
      return LOCAL_CLASS_PLANS_KEY;
    case 'student_credit_grants':
      return LOCAL_CREDIT_GRANTS_KEY;
    case 'student_credit_allocations':
      return LOCAL_CREDIT_ALLOCATIONS_KEY;
    case 'student_credit_ledger':
      return LOCAL_CREDIT_LEDGER_KEY;
    case 'site_settings':
      return LOCAL_SITE_SETTINGS_KEY;
    default:
      return null;
  }
}

function localId(prefix: string) {
  const suffix =
    typeof crypto !== 'undefined' && crypto.randomUUID
      ? crypto.randomUUID()
      : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
  return `${prefix}-${suffix}`;
}

function normalizeLocalRow(table: string, row: Record<string, any>) {
  const now = new Date().toISOString();
  const prefixes: Record<string, string> = {
    bookings: 'local-booking',
    reservation_sessions: 'local-session',
    pricing: 'local-price',
    checkout_orders: 'local-checkout',
    checkout_items: 'local-checkout-item',
    payment_attempts: 'local-payment',
    booking_reschedules: 'local-reschedule',
    notifications: 'local-notification',
    staff_invites: 'local-staff-invite',
    class_plans: 'local-class-plan',
    student_credit_grants: 'local-credit-grant',
    student_credit_allocations: 'local-credit-allocation',
    student_credit_ledger: 'local-credit-ledger',
    site_settings: 'local-setting',
  };
  const normalized = {
    ...row,
    id: row.id ?? localId(prefixes[table] ?? 'local-row'),
    created_at: row.created_at ?? now,
    updated_at: row.updated_at ?? now,
  };
  if (table === 'student_credit_ledger') {
    const lastSequence = readLocalCollection(LOCAL_CREDIT_LEDGER_KEY).reduce(
      (highest: number, entry: any) => Math.max(highest, Number(entry.sequence_no) || 0),
      0,
    );
    return {
      ...normalized,
      sequence_no: row.sequence_no ?? lastSequence + 1,
    };
  }
  if (table === 'staff_invites') {
    return {
      ...normalized,
      token: row.token ?? crypto.randomUUID(),
      status: row.status ?? 'pendente',
      expires_at: row.expires_at ?? new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      accepted_at: row.accepted_at ?? null,
    };
  }
  return normalized;
}

function localRowsFor(table: string): any[] {
  switch (table) {
    case 'profiles':
    case 'profiles_public':
      return [readLocalProfile()];
    case 'user_roles':
      if (isLocalSignupStudent()) {
        return [{ user_id: localUser.id, role: 'aluno' }];
      }
      return [
        { user_id: localUser.id, role: 'aluno' },
        { user_id: localUser.id, role: 'professor' },
        { user_id: localUser.id, role: 'admin' },
      ];
    case 'bookings':
      return readLocalCollection(LOCAL_BOOKINGS_KEY, localBookings);
    case 'reservation_sessions':
      return readLocalCollection(LOCAL_RESERVATION_SESSIONS_KEY, localReservationSessions);
    case 'bookings_occupancy': {
      const now = Date.now();
      return readLocalCollection(LOCAL_BOOKINGS_KEY, localBookings).filter((booking: any) => {
        if (!['pendente', 'confirmada'].includes(booking.status)) return false;
        if (booking.payment_status === 'pago' || booking.status === 'confirmada') return true;
        return booking.hold_expires_at && new Date(booking.hold_expires_at).getTime() > now;
      });
    }
    case 'reservation_session_availability': {
      const now = Date.now();
      const bookings = readLocalCollection(LOCAL_BOOKINGS_KEY, localBookings);
      return readLocalCollection(LOCAL_RESERVATION_SESSIONS_KEY, localReservationSessions)
        .filter((session: any) => session.status === 'open')
        .map((session: any) => {
          const activeBookings = bookings.filter(
            (booking: any) =>
              booking.session_id === session.id &&
              ['pendente', 'confirmada'].includes(booking.status) &&
              (booking.payment_status === 'pago' ||
                booking.status === 'confirmada' ||
                (booking.payment_status === 'pendente' &&
                  booking.hold_expires_at &&
                  new Date(booking.hold_expires_at).getTime() > now)),
          );
          const mine = activeBookings.find((booking: any) => booking.user_id === localUser.id);
          const product = readLocalCollection(LOCAL_PRICING_KEY, localPricing).find(
            (item: any) => item.booking_type === session.product_type,
          );
          return {
            session_id: session.id,
            booking_date: session.booking_date,
            start_hour: session.start_hour,
            professor_id: session.professor_id,
            product_type: session.product_type,
            display_name: product?.display_name ?? 'Aula',
            capacity: session.capacity,
            unit_price_cents: session.unit_price_cents,
            occupied_seats: activeBookings.length,
            available_seats: Math.max(0, session.capacity - activeBookings.length),
            is_full: activeBookings.length >= session.capacity,
            my_booking_id: mine?.id ?? null,
            my_booking_status: mine?.status ?? null,
            my_payment_status: mine?.payment_status ?? null,
            my_payment_method: mine?.payment_method ?? null,
            my_checkout_order_id: mine?.checkout_order_id ?? null,
            my_credit_grant_id: mine?.credit_grant_id ?? null,
            my_hold_expires_at: mine?.hold_expires_at ?? null,
            updated_at: session.updated_at,
          };
        })
        .filter((session: any) => session.occupied_seats > 0);
    }
    case 'pricing':
      return readLocalCollection(LOCAL_PRICING_KEY, localPricing);
    case 'checkout_orders':
      return readLocalCollection(LOCAL_CHECKOUT_ORDERS_KEY);
    case 'checkout_items':
      return readLocalCollection(LOCAL_CHECKOUT_ITEMS_KEY);
    case 'payment_attempts':
      return readLocalCollection(LOCAL_PAYMENT_ATTEMPTS_KEY);
    case 'booking_reschedules':
      return readLocalCollection(LOCAL_BOOKING_RESCHEDULES_KEY);
    case 'notifications':
      return readLocalCollection(LOCAL_NOTIFICATIONS_KEY);
    case 'staff_invites':
      return readLocalCollection(LOCAL_STAFF_INVITES_KEY);
    case 'class_plans':
      return readLocalCollection(LOCAL_CLASS_PLANS_KEY, localClassPlans);
    case 'student_credit_grants':
      return readLocalCollection(LOCAL_CREDIT_GRANTS_KEY);
    case 'student_credit_allocations':
      return readLocalCollection(LOCAL_CREDIT_ALLOCATIONS_KEY);
    case 'student_credit_ledger':
      return readLocalCollection(LOCAL_CREDIT_LEDGER_KEY);
    case 'student_credit_balances': {
      const ledger = readLocalCollection(LOCAL_CREDIT_LEDGER_KEY);
      return readLocalCollection(LOCAL_CREDIT_GRANTS_KEY).map((grant: any) => ({
        grant_id: grant.id,
        user_id: grant.user_id,
        class_plan_id: grant.class_plan_id,
        checkout_order_id: grant.checkout_order_id,
        modality: grant.modality,
        credits_granted: grant.credits_granted,
        available_credits: ledger
          .filter((entry: any) => entry.grant_id === grant.id)
          .reduce((sum: number, entry: any) => sum + Number(entry.credit_delta || 0), 0),
        amount_paid_cents: grant.amount_paid_cents,
        plan_snapshot: grant.plan_snapshot,
        status: grant.status,
        granted_at: grant.granted_at,
        refunded_at: grant.refunded_at,
      }));
    }
    case 'student_credit_summary': {
      const summary = new Map<string, any>();
      for (const balance of localRowsFor('student_credit_balances')) {
        if (balance.status !== 'active') continue;
        const current = summary.get(balance.modality) ?? {
          user_id: balance.user_id,
          modality: balance.modality,
          available_credits: 0,
          credits_acquired: 0,
        };
        current.available_credits += balance.available_credits;
        current.credits_acquired += balance.credits_granted;
        summary.set(balance.modality, current);
      }
      return [...summary.values()];
    }
    case 'site_settings':
      return readLocalCollection(LOCAL_SITE_SETTINGS_KEY, localSiteSettings);
    case 'rpc:list_active_professors':
      return [
        {
          id: localUser.id,
          full_name: localUser.user_metadata.full_name,
          avatar_url: null,
        },
      ];
    case 'rpc:list_students_for_staff': {
      const bookings = readLocalCollection(LOCAL_BOOKINGS_KEY, localBookings);
      return [
        {
          id: localUser.id,
          full_name: localUser.user_metadata.full_name,
          phone: defaultLocalProfile.phone,
          birth_date: defaultLocalProfile.birth_date,
          skill_level: defaultLocalProfile.skill_level,
          bookings: bookings.length,
          attended: bookings.filter((booking: any) => booking.attended === true).length,
          missed: bookings.filter((booking: any) => booking.attended === false).length,
        },
      ];
    }
    case 'rpc:get_student_for_professor':
      return [readLocalProfile()];
    case 'rpc:get_staff_invite_by_token':
      return readLocalCollection(LOCAL_STAFF_INVITES_KEY);
    default:
      return [];
  }
}

function createLocalQueryBuilder(table: string) {
  let singleResult = table === 'rpc:get_student_for_professor';
  let writeOperation: 'insert' | 'update' | 'upsert' | 'delete' | null = null;
  let writePayload: unknown;
  let writeApplied = false;
  let writeRows: any[] | null = null;
  let selectOptions: { count?: string; head?: boolean } | undefined;
  const filters: Array<(row: any) => boolean> = [];
  const orderRules: Array<{ column: string; ascending: boolean }> = [];
  let limitCount: number | null = null;

  const matches = (row: any) => filters.every((filter) => filter(row));
  const rows = () => {
    let current = localRowsFor(table).filter(matches);
    if (orderRules.length) {
      current = [...current].sort((a, b) => {
        for (const rule of orderRules) {
          const av = a?.[rule.column];
          const bv = b?.[rule.column];
          if (av === bv) continue;
          const direction = av == null ? -1 : bv == null ? 1 : av < bv ? -1 : 1;
          return rule.ascending ? direction : -direction;
        }
        return 0;
      });
    }
    return limitCount == null ? current : current.slice(0, limitCount);
  };

  const applyWrite = () => {
    if (!writeOperation || writeApplied) return;
    writeApplied = true;
    if (table === 'profiles' && writeOperation !== 'delete') {
      const patch = Array.isArray(writePayload) ? writePayload[0] : writePayload;
      if (patch && typeof patch === 'object') {
        writeLocalProfile(patch as Record<string, unknown>);
        writeRows = [readLocalProfile()];
      }
      return;
    }

    const storageKey = localStorageKeyForTable(table);
    if (!storageKey) return;

    const current = localRowsFor(table);
    const payloadRows = (Array.isArray(writePayload) ? writePayload : [writePayload]).filter(
      (item): item is Record<string, any> => Boolean(item && typeof item === 'object'),
    );

    if (writeOperation === 'insert') {
      writeRows = payloadRows.map((row) => normalizeLocalRow(table, row));
      writeLocalCollection(storageKey, [...current, ...writeRows]);
      return;
    }

    if (writeOperation === 'update') {
      const patch = payloadRows[0] ?? {};
      writeRows = [];
      const next = current.map((row) => {
        if (!matches(row)) return row;
        const updated = normalizeLocalRow(table, {
          ...row,
          ...patch,
          id: row.id,
          created_at: row.created_at,
        });
        writeRows!.push(updated);
        return updated;
      });
      writeLocalCollection(storageKey, next);
      return;
    }

    if (writeOperation === 'delete') {
      writeRows = current.filter(matches);
      writeLocalCollection(
        storageKey,
        current.filter((row) => !matches(row)),
      );
      return;
    }

    if (writeOperation === 'upsert') {
      const next = [...current];
      writeRows = payloadRows.map((row) => {
        const index = next.findIndex(
          (item) => (row.id && item.id === row.id) || (row.key && item.key === row.key),
        );
        const normalized = normalizeLocalRow(table, index >= 0 ? { ...next[index], ...row } : row);
        if (index >= 0) next[index] = normalized;
        else next.push(normalized);
        return normalized;
      });
      writeLocalCollection(storageKey, next);
    }
  };

  const result = () => {
    applyWrite();
    const currentRows = writeRows ?? rows();
    return {
      data: selectOptions?.head ? null : singleResult ? (currentRows[0] ?? null) : currentRows,
      error: null,
      count: currentRows.length,
    };
  };

  const builder: Record<string, any> = {
    select: (_columns?: string, options?: { count?: string; head?: boolean }) => {
      selectOptions = options;
      return builder;
    },
    insert: (payload: unknown) => {
      writeOperation = 'insert';
      writePayload = payload;
      return builder;
    },
    update: (payload: unknown) => {
      writeOperation = 'update';
      writePayload = payload;
      return builder;
    },
    upsert: (payload: unknown) => {
      writeOperation = 'upsert';
      writePayload = payload;
      return builder;
    },
    delete: () => {
      writeOperation = 'delete';
      return builder;
    },
    eq: (column: string, value: unknown) => {
      filters.push((row) => row?.[column] === value);
      return builder;
    },
    neq: (column: string, value: unknown) => {
      filters.push((row) => row?.[column] !== value);
      return builder;
    },
    gt: (column: string, value: any) => {
      filters.push((row) => row?.[column] > value);
      return builder;
    },
    gte: (column: string, value: any) => {
      filters.push((row) => row?.[column] >= value);
      return builder;
    },
    lt: (column: string, value: any) => {
      filters.push((row) => row?.[column] < value);
      return builder;
    },
    lte: (column: string, value: any) => {
      filters.push((row) => row?.[column] <= value);
      return builder;
    },
    in: (column: string, values: unknown[]) => {
      filters.push((row) => values.includes(row?.[column]));
      return builder;
    },
    is: () => builder,
    not: () => builder,
    or: () => builder,
    filter: () => builder,
    match: () => builder,
    like: () => builder,
    ilike: () => builder,
    contains: () => builder,
    range: (from: number, to: number) => {
      limitCount = Math.max(0, to - from + 1);
      return builder;
    },
    order: (column: string, options?: { ascending?: boolean }) => {
      orderRules.push({ column, ascending: options?.ascending !== false });
      return builder;
    },
    limit: (count: number) => {
      limitCount = count;
      return builder;
    },
    maybeSingle: () => {
      singleResult = true;
      return builder;
    },
    single: () => {
      singleResult = true;
      return builder;
    },
    then: (
      resolve: (value: ReturnType<typeof result>) => unknown,
      reject?: (reason: unknown) => unknown,
    ) => Promise.resolve(result()).then(resolve, reject),
    catch: (reject: (reason: unknown) => unknown) => Promise.resolve(result()).catch(reject),
    finally: (onFinally: () => void) => Promise.resolve(result()).finally(onFinally),
  };

  return builder;
}

function createLocalSupabaseClient() {
  console.warn(
    '[Supabase] Local mode: environment variables are not configured. Using local development auth and mock data.',
  );

  return {
    auth: {
      getSession: async () => ({ data: { session: readLocalSession() }, error: null }),
      getUser: async () => {
        const session = readLocalSession();
        return session
          ? { data: { user: session.user }, error: null }
          : {
              data: { user: null },
              error: { message: 'Local user is not signed in.', name: 'LocalAuthRequired' },
            };
      },
      signUp: async ({ email }: { email: string }) => {
        if (email.trim().toLowerCase() !== LOCAL_DEV_EMAIL) {
          writeLocalSession(true);
          writeLocalSignupStudent(true);
          return {
            data: {
              user: {
                ...localUser,
                email: email.trim().toLowerCase(),
                identities: [{ id: localUser.id }],
              },
              session: localSession,
            },
            error: null,
          };
        }
        writeLocalSession(true);
        writeLocalSignupStudent(false);
        return {
          data: {
            user: { ...localUser, identities: [{ id: localUser.id }] },
            session: localSession,
          },
          error: null,
        };
      },
      signInWithPassword: async ({ email, password }: { email: string; password: string }) => {
        if (email.trim().toLowerCase() !== LOCAL_DEV_EMAIL || password !== LOCAL_DEV_PASSWORD) {
          return {
            data: { user: null, session: null },
            error: {
              message: `Login local: use ${LOCAL_DEV_EMAIL} / ${LOCAL_DEV_PASSWORD}.`,
              name: 'LocalInvalidCredentials',
            },
          };
        }
        writeLocalSession(true);
        writeLocalSignupStudent(false);
        return { data: { user: localUser, session: localSession }, error: null };
      },
      resend: async () => ({ data: {}, error: null }),
      signOut: async () => {
        writeLocalSession(false);
        return { error: null };
      },
      resetPasswordForEmail: async () => ({ data: {}, error: localSupabaseError }),
      updateUser: async () => ({ data: { user: localUser }, error: localSupabaseError }),
      onAuthStateChange: (
        callback: (event: string, session: typeof localSession | null) => void,
      ) => {
        queueMicrotask(() => callback('INITIAL_SESSION', readLocalSession()));
        return {
          data: {
            subscription: {
              unsubscribe: () => undefined,
            },
          },
        };
      },
      setSession: async () => ({ data: { session: null, user: null }, error: localSupabaseError }),
    },
    from: (table: string) => createLocalQueryBuilder(table),
    rpc: (functionName: string, args?: Record<string, unknown>) => {
      if (functionName === 'accept_staff_invite') {
        return Promise.resolve({ data: 'professor', error: null });
      }
      const query = createLocalQueryBuilder(`rpc:${functionName}`);
      if (functionName === 'get_staff_invite_by_token' && args?._token) {
        return query.eq('token', args._token);
      }
      return query;
    },
    channel: () => ({
      on: function () {
        return this;
      },
      subscribe: function () {
        return this;
      },
    }),
    removeChannel: async () => ({ error: null }),
    storage: {
      from: () => ({
        upload: async () => ({ data: null, error: localSupabaseError }),
        remove: async () => ({ data: null, error: localSupabaseError }),
        createSignedUrl: async () => ({ data: null, error: localSupabaseError }),
      }),
    },
  };
}

function createSupabaseClient() {
  if (import.meta.env.VITE_ENABLE_LOCAL_MODE === 'true') {
    return createLocalSupabaseClient() as unknown as ReturnType<typeof createClient<Database>>;
  }

  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    if (!canUseLocalSupabaseMode()) {
      throw new Error(
        'Supabase configuration is required. Local mock mode is disabled for this build.',
      );
    }
    return createLocalSupabaseClient() as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
