/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as ConviteCodeRouteImport } from './routes/convite.$code'
import { Route as AuthenticatedPitchRouteImport } from './routes/_authenticated/pitch'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppMatchAbertoRouteImport } from './routes/_authenticated/app.match-aberto'
import { Route as AuthenticatedAppLojaRouteImport } from './routes/_authenticated/app.loja'
import { Route as AuthenticatedAppIndicacoesRouteImport } from './routes/_authenticated/app.indicacoes'
import { Route as AuthenticatedAppFeedbackRouteImport } from './routes/_authenticated/app.feedback'
import { Route as AuthenticatedAppEvolucaoRouteImport } from './routes/_authenticated/app.evolucao'
import { Route as AuthenticatedAppAulasRouteImport } from './routes/_authenticated/app.aulas'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAdminTermosRouteImport } from './routes/_authenticated/admin.termos'
import { Route as AuthenticatedAdminReservasRouteImport } from './routes/_authenticated/admin.reservas'
import { Route as AuthenticatedAdminOperadorasRouteImport } from './routes/_authenticated/admin.operadoras'
import { Route as AuthenticatedAdminMatchAbertoRouteImport } from './routes/_authenticated/admin.match-aberto'
import { Route as AuthenticatedAdminLojaRouteImport } from './routes/_authenticated/admin.loja'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminIndicacoesRouteImport } from './routes/_authenticated/admin.indicacoes'
import { Route as AuthenticatedAdminGamificacaoRouteImport } from './routes/_authenticated/admin.gamificacao'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminFeedbacksRouteImport } from './routes/_authenticated/admin.feedbacks'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminContratoConfigRouteImport } from './routes/_authenticated/admin.contrato-config'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminCoachPerfisRouteImport } from './routes/_authenticated/admin.coach-perfis'
import { Route as AuthenticatedAdminBloqueiosRouteImport } from './routes/_authenticated/admin.bloqueios'
import { Route as AuthenticatedAdminAvaliacoesRouteImport } from './routes/_authenticated/admin.avaliacoes'
import { Route as AuthenticatedAdminAulasTemplateRouteImport } from './routes/_authenticated/admin.aulas-template'
import { Route as AuthenticatedAdminAulasPlanosRouteImport } from './routes/_authenticated/admin.aulas-planos'
import { Route as AuthenticatedAdminAulasContratosRouteImport } from './routes/_authenticated/admin.aulas-contratos'
import { Route as AuthenticatedAdminAlunosRouteImport } from './routes/_authenticated/admin.alunos'
import { Route as AuthenticatedAdminAlunoIdRouteImport } from './routes/_authenticated/admin.aluno.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteCodeRoute = ConviteCodeRouteImport.update({
  id: '/convite/$code',
  path: '/convite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPitchRoute = AuthenticatedPitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMatchAbertoRoute =
  AuthenticatedAppMatchAbertoRouteImport.update({
    id: '/match-aberto',
    path: '/match-aberto',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLojaRoute = AuthenticatedAppLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIndicacoesRoute =
  AuthenticatedAppIndicacoesRouteImport.update({
    id: '/indicacoes',
    path: '/indicacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFeedbackRoute =
  AuthenticatedAppFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEvolucaoRoute =
  AuthenticatedAppEvolucaoRouteImport.update({
    id: '/evolucao',
    path: '/evolucao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAulasRoute = AuthenticatedAppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminTermosRoute =
  AuthenticatedAdminTermosRouteImport.update({
    id: '/termos',
    path: '/termos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReservasRoute =
  AuthenticatedAdminReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOperadorasRoute =
  AuthenticatedAdminOperadorasRouteImport.update({
    id: '/operadoras',
    path: '/operadoras',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMatchAbertoRoute =
  AuthenticatedAdminMatchAbertoRouteImport.update({
    id: '/match-aberto',
    path: '/match-aberto',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLojaRoute = AuthenticatedAdminLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIndicacoesRoute =
  AuthenticatedAdminIndicacoesRouteImport.update({
    id: '/indicacoes',
    path: '/indicacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGamificacaoRoute =
  AuthenticatedAdminGamificacaoRouteImport.update({
    id: '/gamificacao',
    path: '/gamificacao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbacksRoute =
  AuthenticatedAdminFeedbacksRouteImport.update({
    id: '/feedbacks',
    path: '/feedbacks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContratoConfigRoute =
  AuthenticatedAdminContratoConfigRouteImport.update({
    id: '/contrato-config',
    path: '/contrato-config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoachPerfisRoute =
  AuthenticatedAdminCoachPerfisRouteImport.update({
    id: '/coach-perfis',
    path: '/coach-perfis',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBloqueiosRoute =
  AuthenticatedAdminBloqueiosRouteImport.update({
    id: '/bloqueios',
    path: '/bloqueios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAvaliacoesRoute =
  AuthenticatedAdminAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAulasTemplateRoute =
  AuthenticatedAdminAulasTemplateRouteImport.update({
    id: '/aulas-template',
    path: '/aulas-template',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAulasPlanosRoute =
  AuthenticatedAdminAulasPlanosRouteImport.update({
    id: '/aulas-planos',
    path: '/aulas-planos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAulasContratosRoute =
  AuthenticatedAdminAulasContratosRouteImport.update({
    id: '/aulas-contratos',
    path: '/aulas-contratos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlunosRoute =
  AuthenticatedAdminAlunosRouteImport.update({
    id: '/alunos',
    path: '/alunos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlunoIdRoute =
  AuthenticatedAdminAlunoIdRouteImport.update({
    id: '/aluno/$id',
    path: '/aluno/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/pitch': typeof AuthenticatedPitchRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/admin/aulas-contratos': typeof AuthenticatedAdminAulasContratosRoute
  '/admin/aulas-planos': typeof AuthenticatedAdminAulasPlanosRoute
  '/admin/aulas-template': typeof AuthenticatedAdminAulasTemplateRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/bloqueios': typeof AuthenticatedAdminBloqueiosRoute
  '/admin/coach-perfis': typeof AuthenticatedAdminCoachPerfisRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/contrato-config': typeof AuthenticatedAdminContratoConfigRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/feedbacks': typeof AuthenticatedAdminFeedbacksRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/gamificacao': typeof AuthenticatedAdminGamificacaoRoute
  '/admin/indicacoes': typeof AuthenticatedAdminIndicacoesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/loja': typeof AuthenticatedAdminLojaRoute
  '/admin/match-aberto': typeof AuthenticatedAdminMatchAbertoRoute
  '/admin/operadoras': typeof AuthenticatedAdminOperadorasRoute
  '/admin/reservas': typeof AuthenticatedAdminReservasRoute
  '/admin/termos': typeof AuthenticatedAdminTermosRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/aulas': typeof AuthenticatedAppAulasRoute
  '/app/evolucao': typeof AuthenticatedAppEvolucaoRoute
  '/app/feedback': typeof AuthenticatedAppFeedbackRoute
  '/app/indicacoes': typeof AuthenticatedAppIndicacoesRoute
  '/app/loja': typeof AuthenticatedAppLojaRoute
  '/app/match-aberto': typeof AuthenticatedAppMatchAbertoRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/aluno/$id': typeof AuthenticatedAdminAlunoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pitch': typeof AuthenticatedPitchRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/admin/aulas-contratos': typeof AuthenticatedAdminAulasContratosRoute
  '/admin/aulas-planos': typeof AuthenticatedAdminAulasPlanosRoute
  '/admin/aulas-template': typeof AuthenticatedAdminAulasTemplateRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/bloqueios': typeof AuthenticatedAdminBloqueiosRoute
  '/admin/coach-perfis': typeof AuthenticatedAdminCoachPerfisRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/contrato-config': typeof AuthenticatedAdminContratoConfigRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/feedbacks': typeof AuthenticatedAdminFeedbacksRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/gamificacao': typeof AuthenticatedAdminGamificacaoRoute
  '/admin/indicacoes': typeof AuthenticatedAdminIndicacoesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/loja': typeof AuthenticatedAdminLojaRoute
  '/admin/match-aberto': typeof AuthenticatedAdminMatchAbertoRoute
  '/admin/operadoras': typeof AuthenticatedAdminOperadorasRoute
  '/admin/reservas': typeof AuthenticatedAdminReservasRoute
  '/admin/termos': typeof AuthenticatedAdminTermosRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/aulas': typeof AuthenticatedAppAulasRoute
  '/app/evolucao': typeof AuthenticatedAppEvolucaoRoute
  '/app/feedback': typeof AuthenticatedAppFeedbackRoute
  '/app/indicacoes': typeof AuthenticatedAppIndicacoesRoute
  '/app/loja': typeof AuthenticatedAppLojaRoute
  '/app/match-aberto': typeof AuthenticatedAppMatchAbertoRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/aluno/$id': typeof AuthenticatedAdminAlunoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/pitch': typeof AuthenticatedPitchRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_authenticated/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/_authenticated/admin/aulas-contratos': typeof AuthenticatedAdminAulasContratosRoute
  '/_authenticated/admin/aulas-planos': typeof AuthenticatedAdminAulasPlanosRoute
  '/_authenticated/admin/aulas-template': typeof AuthenticatedAdminAulasTemplateRoute
  '/_authenticated/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/_authenticated/admin/bloqueios': typeof AuthenticatedAdminBloqueiosRoute
  '/_authenticated/admin/coach-perfis': typeof AuthenticatedAdminCoachPerfisRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/contrato-config': typeof AuthenticatedAdminContratoConfigRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/feedbacks': typeof AuthenticatedAdminFeedbacksRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/gamificacao': typeof AuthenticatedAdminGamificacaoRoute
  '/_authenticated/admin/indicacoes': typeof AuthenticatedAdminIndicacoesRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/loja': typeof AuthenticatedAdminLojaRoute
  '/_authenticated/admin/match-aberto': typeof AuthenticatedAdminMatchAbertoRoute
  '/_authenticated/admin/operadoras': typeof AuthenticatedAdminOperadorasRoute
  '/_authenticated/admin/reservas': typeof AuthenticatedAdminReservasRoute
  '/_authenticated/admin/termos': typeof AuthenticatedAdminTermosRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/aulas': typeof AuthenticatedAppAulasRoute
  '/_authenticated/app/evolucao': typeof AuthenticatedAppEvolucaoRoute
  '/_authenticated/app/feedback': typeof AuthenticatedAppFeedbackRoute
  '/_authenticated/app/indicacoes': typeof AuthenticatedAppIndicacoesRoute
  '/_authenticated/app/loja': typeof AuthenticatedAppLojaRoute
  '/_authenticated/app/match-aberto': typeof AuthenticatedAppMatchAbertoRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/aluno/$id': typeof AuthenticatedAdminAlunoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/pitch'
    | '/convite/$code'
    | '/convite/$token'
    | '/admin/alunos'
    | '/admin/aulas-contratos'
    | '/admin/aulas-planos'
    | '/admin/aulas-template'
    | '/admin/avaliacoes'
    | '/admin/bloqueios'
    | '/admin/coach-perfis'
    | '/admin/configuracoes'
    | '/admin/contrato-config'
    | '/admin/equipe'
    | '/admin/feedbacks'
    | '/admin/financeiro'
    | '/admin/gamificacao'
    | '/admin/indicacoes'
    | '/admin/leads'
    | '/admin/loja'
    | '/admin/match-aberto'
    | '/admin/operadoras'
    | '/admin/reservas'
    | '/admin/termos'
    | '/app/agenda'
    | '/app/aulas'
    | '/app/evolucao'
    | '/app/feedback'
    | '/app/indicacoes'
    | '/app/loja'
    | '/app/match-aberto'
    | '/app/perfil'
    | '/admin/'
    | '/app/'
    | '/admin/aluno/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pitch'
    | '/convite/$code'
    | '/convite/$token'
    | '/admin/alunos'
    | '/admin/aulas-contratos'
    | '/admin/aulas-planos'
    | '/admin/aulas-template'
    | '/admin/avaliacoes'
    | '/admin/bloqueios'
    | '/admin/coach-perfis'
    | '/admin/configuracoes'
    | '/admin/contrato-config'
    | '/admin/equipe'
    | '/admin/feedbacks'
    | '/admin/financeiro'
    | '/admin/gamificacao'
    | '/admin/indicacoes'
    | '/admin/leads'
    | '/admin/loja'
    | '/admin/match-aberto'
    | '/admin/operadoras'
    | '/admin/reservas'
    | '/admin/termos'
    | '/app/agenda'
    | '/app/aulas'
    | '/app/evolucao'
    | '/app/feedback'
    | '/app/indicacoes'
    | '/app/loja'
    | '/app/match-aberto'
    | '/app/perfil'
    | '/admin'
    | '/app'
    | '/admin/aluno/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/pitch'
    | '/convite/$code'
    | '/convite/$token'
    | '/_authenticated/admin/alunos'
    | '/_authenticated/admin/aulas-contratos'
    | '/_authenticated/admin/aulas-planos'
    | '/_authenticated/admin/aulas-template'
    | '/_authenticated/admin/avaliacoes'
    | '/_authenticated/admin/bloqueios'
    | '/_authenticated/admin/coach-perfis'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/contrato-config'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/feedbacks'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/gamificacao'
    | '/_authenticated/admin/indicacoes'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/loja'
    | '/_authenticated/admin/match-aberto'
    | '/_authenticated/admin/operadoras'
    | '/_authenticated/admin/reservas'
    | '/_authenticated/admin/termos'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/aulas'
    | '/_authenticated/app/evolucao'
    | '/_authenticated/app/feedback'
    | '/_authenticated/app/indicacoes'
    | '/_authenticated/app/loja'
    | '/_authenticated/app/match-aberto'
    | '/_authenticated/app/perfil'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/aluno/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConviteCodeRoute: typeof ConviteCodeRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$code': {
      id: '/convite/$code'
      path: '/convite/$code'
      fullPath: '/convite/$code'
      preLoaderRoute: typeof ConviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pitch': {
      id: '/_authenticated/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof AuthenticatedPitchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/match-aberto': {
      id: '/_authenticated/app/match-aberto'
      path: '/match-aberto'
      fullPath: '/app/match-aberto'
      preLoaderRoute: typeof AuthenticatedAppMatchAbertoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/loja': {
      id: '/_authenticated/app/loja'
      path: '/loja'
      fullPath: '/app/loja'
      preLoaderRoute: typeof AuthenticatedAppLojaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/indicacoes': {
      id: '/_authenticated/app/indicacoes'
      path: '/indicacoes'
      fullPath: '/app/indicacoes'
      preLoaderRoute: typeof AuthenticatedAppIndicacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/feedback': {
      id: '/_authenticated/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AuthenticatedAppFeedbackRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/evolucao': {
      id: '/_authenticated/app/evolucao'
      path: '/evolucao'
      fullPath: '/app/evolucao'
      preLoaderRoute: typeof AuthenticatedAppEvolucaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/aulas': {
      id: '/_authenticated/app/aulas'
      path: '/aulas'
      fullPath: '/app/aulas'
      preLoaderRoute: typeof AuthenticatedAppAulasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/termos': {
      id: '/_authenticated/admin/termos'
      path: '/termos'
      fullPath: '/admin/termos'
      preLoaderRoute: typeof AuthenticatedAdminTermosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reservas': {
      id: '/_authenticated/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AuthenticatedAdminReservasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/operadoras': {
      id: '/_authenticated/admin/operadoras'
      path: '/operadoras'
      fullPath: '/admin/operadoras'
      preLoaderRoute: typeof AuthenticatedAdminOperadorasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/match-aberto': {
      id: '/_authenticated/admin/match-aberto'
      path: '/match-aberto'
      fullPath: '/admin/match-aberto'
      preLoaderRoute: typeof AuthenticatedAdminMatchAbertoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/loja': {
      id: '/_authenticated/admin/loja'
      path: '/loja'
      fullPath: '/admin/loja'
      preLoaderRoute: typeof AuthenticatedAdminLojaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/indicacoes': {
      id: '/_authenticated/admin/indicacoes'
      path: '/indicacoes'
      fullPath: '/admin/indicacoes'
      preLoaderRoute: typeof AuthenticatedAdminIndicacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gamificacao': {
      id: '/_authenticated/admin/gamificacao'
      path: '/gamificacao'
      fullPath: '/admin/gamificacao'
      preLoaderRoute: typeof AuthenticatedAdminGamificacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feedbacks': {
      id: '/_authenticated/admin/feedbacks'
      path: '/feedbacks'
      fullPath: '/admin/feedbacks'
      preLoaderRoute: typeof AuthenticatedAdminFeedbacksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contrato-config': {
      id: '/_authenticated/admin/contrato-config'
      path: '/contrato-config'
      fullPath: '/admin/contrato-config'
      preLoaderRoute: typeof AuthenticatedAdminContratoConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coach-perfis': {
      id: '/_authenticated/admin/coach-perfis'
      path: '/coach-perfis'
      fullPath: '/admin/coach-perfis'
      preLoaderRoute: typeof AuthenticatedAdminCoachPerfisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bloqueios': {
      id: '/_authenticated/admin/bloqueios'
      path: '/bloqueios'
      fullPath: '/admin/bloqueios'
      preLoaderRoute: typeof AuthenticatedAdminBloqueiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/avaliacoes': {
      id: '/_authenticated/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAdminAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aulas-template': {
      id: '/_authenticated/admin/aulas-template'
      path: '/aulas-template'
      fullPath: '/admin/aulas-template'
      preLoaderRoute: typeof AuthenticatedAdminAulasTemplateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aulas-planos': {
      id: '/_authenticated/admin/aulas-planos'
      path: '/aulas-planos'
      fullPath: '/admin/aulas-planos'
      preLoaderRoute: typeof AuthenticatedAdminAulasPlanosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aulas-contratos': {
      id: '/_authenticated/admin/aulas-contratos'
      path: '/aulas-contratos'
      fullPath: '/admin/aulas-contratos'
      preLoaderRoute: typeof AuthenticatedAdminAulasContratosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/alunos': {
      id: '/_authenticated/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AuthenticatedAdminAlunosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aluno/$id': {
      id: '/_authenticated/admin/aluno/$id'
      path: '/aluno/$id'
      fullPath: '/admin/aluno/$id'
      preLoaderRoute: typeof AuthenticatedAdminAlunoIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAlunosRoute: typeof AuthenticatedAdminAlunosRoute
  AuthenticatedAdminAulasContratosRoute: typeof AuthenticatedAdminAulasContratosRoute
  AuthenticatedAdminAulasPlanosRoute: typeof AuthenticatedAdminAulasPlanosRoute
  AuthenticatedAdminAulasTemplateRoute: typeof AuthenticatedAdminAulasTemplateRoute
  AuthenticatedAdminAvaliacoesRoute: typeof AuthenticatedAdminAvaliacoesRoute
  AuthenticatedAdminBloqueiosRoute: typeof AuthenticatedAdminBloqueiosRoute
  AuthenticatedAdminCoachPerfisRoute: typeof AuthenticatedAdminCoachPerfisRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminContratoConfigRoute: typeof AuthenticatedAdminContratoConfigRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminFeedbacksRoute: typeof AuthenticatedAdminFeedbacksRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminGamificacaoRoute: typeof AuthenticatedAdminGamificacaoRoute
  AuthenticatedAdminIndicacoesRoute: typeof AuthenticatedAdminIndicacoesRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminLojaRoute: typeof AuthenticatedAdminLojaRoute
  AuthenticatedAdminMatchAbertoRoute: typeof AuthenticatedAdminMatchAbertoRoute
  AuthenticatedAdminOperadorasRoute: typeof AuthenticatedAdminOperadorasRoute
  AuthenticatedAdminReservasRoute: typeof AuthenticatedAdminReservasRoute
  AuthenticatedAdminTermosRoute: typeof AuthenticatedAdminTermosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAlunoIdRoute: typeof AuthenticatedAdminAlunoIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAlunosRoute: AuthenticatedAdminAlunosRoute,
  AuthenticatedAdminAulasContratosRoute: AuthenticatedAdminAulasContratosRoute,
  AuthenticatedAdminAulasPlanosRoute: AuthenticatedAdminAulasPlanosRoute,
  AuthenticatedAdminAulasTemplateRoute: AuthenticatedAdminAulasTemplateRoute,
  AuthenticatedAdminAvaliacoesRoute: AuthenticatedAdminAvaliacoesRoute,
  AuthenticatedAdminBloqueiosRoute: AuthenticatedAdminBloqueiosRoute,
  AuthenticatedAdminCoachPerfisRoute: AuthenticatedAdminCoachPerfisRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminContratoConfigRoute: AuthenticatedAdminContratoConfigRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminFeedbacksRoute: AuthenticatedAdminFeedbacksRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminGamificacaoRoute: AuthenticatedAdminGamificacaoRoute,
  AuthenticatedAdminIndicacoesRoute: AuthenticatedAdminIndicacoesRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminLojaRoute: AuthenticatedAdminLojaRoute,
  AuthenticatedAdminMatchAbertoRoute: AuthenticatedAdminMatchAbertoRoute,
  AuthenticatedAdminOperadorasRoute: AuthenticatedAdminOperadorasRoute,
  AuthenticatedAdminReservasRoute: AuthenticatedAdminReservasRoute,
  AuthenticatedAdminTermosRoute: AuthenticatedAdminTermosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAlunoIdRoute: AuthenticatedAdminAlunoIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppAulasRoute: typeof AuthenticatedAppAulasRoute
  AuthenticatedAppEvolucaoRoute: typeof AuthenticatedAppEvolucaoRoute
  AuthenticatedAppFeedbackRoute: typeof AuthenticatedAppFeedbackRoute
  AuthenticatedAppIndicacoesRoute: typeof AuthenticatedAppIndicacoesRoute
  AuthenticatedAppLojaRoute: typeof AuthenticatedAppLojaRoute
  AuthenticatedAppMatchAbertoRoute: typeof AuthenticatedAppMatchAbertoRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppAulasRoute: AuthenticatedAppAulasRoute,
  AuthenticatedAppEvolucaoRoute: AuthenticatedAppEvolucaoRoute,
  AuthenticatedAppFeedbackRoute: AuthenticatedAppFeedbackRoute,
  AuthenticatedAppIndicacoesRoute: AuthenticatedAppIndicacoesRoute,
  AuthenticatedAppLojaRoute: AuthenticatedAppLojaRoute,
  AuthenticatedAppMatchAbertoRoute: AuthenticatedAppMatchAbertoRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedPitchRoute: typeof AuthenticatedPitchRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedPitchRoute: AuthenticatedPitchRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConviteCodeRoute: ConviteCodeRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
